version: "3.9"

services:
  palworld_server:
    build: .
    platform: linux/amd64
    container_name: "palworld_server"
    volumes:
      - "./palworld_data:/app/palworld-dedicated:rw"
    ports:
      - "8211:8211/udp"
      - "27015:27015"
    environment:
      - ADDITIONAL_ARGS=-EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
    stdin_open: true
    tty: true
